### ISSUE TITLE
How do I use this script (serious help needed)?

### ISSUE THREAD

**Issue by KatieBelli** [ittiam-systems/libmpegh#11]
Hello, I'm new to using scripts/programming. I've asked on several websites how to use your script but no one answers me. I hope you can help me.

I have MS Visual Studio 2017. I know how to change the path with "cd" (CMD) and how to use OrpheusDL (Tidal).

But I found no clue which files I need to open, how to change the configuration, or which file I need to start decoding my 360 audio files.

Can you please help me? I don't know where else I can ask for help. I appreciate any help I can get.

PS: I was able to change the line 1483 from what I saw on this post: https://github.com/ittiam-systems/libmpegh/issues/1#issuecomment-1072164585

**Comment by KatieBelli** [comment]
Just solved this by myself. It's easier than I thought. Have a nice day!

**Comment by notjsng** [comment]
hello, could you help me please
