### ISSUE TITLE
"core coder module :Initialization: : Insufficient input bytes"

### ISSUE THREAD

**Issue by ThreeDeeJay** [ittiam-systems/libmpegh#17]
I've been trying to decode [mpeg-h_3d_audio_mhm1_sample.mp4](https://samples.ffmpeg.org/A-codecs/MPEGH3D/mpeg-h_3d_audio_mhm1_sample.mp4) ([original source](https://patchwork.ffmpeg.org/project/ffmpeg/patch/1571299028-15927-1-git-send-email-Yuki.Tsuchiya@sony.com/)) using the [latest ia_mpeghd_testbench.exe](https://github.com/ThreeDeeJay/libmpegh/releases/download/latest/ia_mpeghd_testbench.exe) like:
`ia_mpeghd_testbench.exe -ifile:mpeg-h_3d_audio_mhm1_sample.mp4 -ofile:mpeg-h_3d_audio_mhm1_sample.wav -cicp:7`

However, it hangs for a long time then outputs:
```
                       ITTIAM SYSTEMS PVT LTD, BANGALORE
                             http:\\www.ittiam.com
                     IA_MPEG_H_3D_AUD_DEC_MSVC $Rev: 1.2 $


fatal error: Ittiam mpegh_dec  core coder module :Initialization: : Initialization fatal error
```
MediaInfo:
```
Format                      : MPEG-4
Format profile              : Base Media / Version 2
Codec ID                    : mp42 (mp42/isom)
File size                   : 8.83 MiB
Duration                    : 46 s 0 ms
Overall bit rate            : 1 610 kb/s
Encoded date                : UTC 2019-10-24 08:16:45
Tagged date                 : UTC 2019-10-24 08:16:45

Audio
ID                          : 1
Format                      : MPEG-H 3D Audio
Format profile              : LC@L4
Codec ID                    : mhm1
Duration                    : 46 s 0 ms
Source duration             : 46 s 80 ms
Bit rate                    : 1 604 kb/s
Channel(s)                  : 24 channels (22.2)
Channel layout              : Lw Rw C LFE Lb Rb L R Cb LFE2 Lss Rss Tfl Tfr Tfc Tc Tbl Tbr Tll Tsr Tbc Bfc Bfl Bfr
Sampling rate               : 48.0 kHz
Frame rate                  : 46.875 FPS (1024 SPF)
Stream size                 : 8.80 MiB (100%)
Source stream size          : 8.81 MiB (100%)
Encoded date                : UTC 2019-10-24 08:16:45
Tagged date                 : UTC 2019-10-24 08:16:45
Signal group #1             : 24 objects
 Type                       : Object
 Number of objects          : 24 objects
Codec configuration box     : mhaC
```

I also tried decoding a **[remuxing](https://patchwork.ffmpeg.org/project/ffmpeg/patch/1571299028-15927-1-git-send-email-Yuki.Tsuchiya@sony.com/)** with an old ffmpeg build (since apparently it's been superseeded/removed) ([listed support](https://gist.github.com/Jaid/c12f9eafa743f6662e876f6ecfcbcbec#file-codecs-txt-L393)) and then decoding [mpeg-h_3d_audio_mhm1_sample_REMUX.mp4](https://user-images.githubusercontent.com/71472458/194530779-98e52b1d-1c2e-4f1f-ba43-433a7952b819.mp4), but with the same results.
Other MPEG-H 3D files convert fine, so I'm not sure if this is an issue with the file or the decoder.
In case it's the file, are there any test files like channel identification for MPEG-H 3D?

**Comment by SakethSathuvalli** [comment]
Hi @ThreeDeeJay,

The issue you are facing is same as the one reported in the [thread](https://github.com/ittiam-systems/libmpegh/issues/1) -

The solution is presented at : https://github.com/ittiam-systems/libmpegh/issues/1#issuecomment-1041358839

We have verified this at our end and the decoding happens fine for this stream with the above fix.

Thanks,
Saketh

**Comment by ThreeDeeJay** [comment]
Ohh, my apologies. I wasn't aware it had been reported already.
I'll give it a shot! 👍
