### ISSUE TITLE
I can't decode the audio stream

### ISSUE THREAD

**Issue by Emixjackox** [ittiam-systems/libmpegh#18]
Hi, i built this tool on OSX environment, i used it to decode an audio stream mha1 in a container .mp4, the result is this:
<img width="552" alt="Schermata 2022-10-13 alle 21 42 35" src="https://user-images.githubusercontent.com/115740344/195694273-b816df01-b017-48ce-96cd-fce93fad3643.png">

more info:
<img width="999" alt="Schermata 2022-10-13 alle 21 44 14" src="https://user-images.githubusercontent.com/115740344/195694577-83ccc083-078b-41dd-bc16-11ebea0a54d4.png">

**Comment by SakethSathuvalli** [comment]
Hi,

The issue you are facing could be same as the one reported in the https://github.com/ittiam-systems/libmpegh/issues/1

Did you try the solution is presented at : https://github.com/ittiam-systems/libmpegh/issues/1#issuecomment-1041358839 ?


If not we recommend you try the above workaround and let us know if the the issue still persists.

Thanks!

**Comment by Emixjackox** [comment]
I did not understand how to get around the decoder by commenting on the line. What exactly should I do?

**Comment by SakethSathuvalli** [comment]
> I did not understand how to get around the decoder by commenting on the line. What exactly should I do?

Please check the steps in this [comment](https://github.com/ittiam-systems/libmpegh/issues/1#issuecomment-1064887503) once

**Comment by Emixjackox** [comment]
the comment line corresponds to the file ia_core_coder_init_config.c, I'm using the latest build, 1.2. I tried but it always gives me the same result. This is the file I am trying to decode https://we.tl/t-e3BBPS96zD

**Comment by SakethSathuvalli** [comment]
Hi @Emixjackox,

Are You saying that You are not able to decode the said file with executable that is built after commenting line 1483 of file ia_core_coder_init_config.c ?

Can You please let us know Where you got this file from - what is the source ?

Thanks!

**Comment by Emixjackox** [comment]
> > Hi @Emixjackox,
> > Are You saying that You are not able to decode the said file with executable that is built after commenting line 1483 of file ia_core_coder_init_config.c ?
> > Can You please let us know Where you got this file from - what is the source ?
> > Thanks!
> 
> Hi @Emixjackox ,
> 
> Did You try the suggested workaround ?

I gave up on decoding the level 4 file with the decoder since I didn't understand how to rebuild after modifying line 1483 of the code. I also used your decoder with a level 3 .mp4 file and it worked, for the first time I saw the decoder in action and it is very fast. Do you know if ffmpeg or mp4-box are able to extract mhas from mp4 container?

**Comment by SakethSathuvalli** [comment]
> > > Hi @Emixjackox,
> > > Are You saying that You are not able to decode the said file with executable that is built after commenting line 1483 of file ia_core_coder_init_config.c ?
> > > Can You please let us know Where you got this file from - what is the source ?
> > > Thanks!
> > 
> > 
> > Hi @Emixjackox ,
> > Did You try the suggested workaround ?
> 
> I gave up on decoding the level 4 file with the decoder since I didn't understand how to rebuild after modifying line 1483 of the code. I also used your decoder with a level 3 .mp4 file and it worked, for the first time I saw the decoder in action and it is very fast. Do you know if ffmpeg or mp4-box are able to extract mhas from mp4 container?

Hi @Emixjackox,

After commenting the line as suggested in the workaround, the build procedure is pretty much same the as procedure You followed for the first time build. Please let us know if you still face issues even with the workaround.
Good to know that You are able to run level 3.

Regarding extraction of mhas from mp4, We have our own extractor tool as part of our [encoder ](https://github.com/ittiam-systems/libmpeghe) workspace.

**Comment by SakethSathuvalli** [comment]
> > > > Hi @Emixjackox,
> > > > Are You saying that You are not able to decode the said file with executable that is built after commenting line 1483 of file ia_core_coder_init_config.c ?
> > > > Can You please let us know Where you got this file from - what is the source ?
> > > > Thanks!
> > > 
> > > 
> > > Hi @Emixjackox ,
> > > Did You try the suggested workaround ?
> > 
> > 
> > I gave up on decoding the level 4 file with the decoder since I didn't understand how to rebuild after modifying line 1483 of the code. I also used your decoder with a level 3 .mp4 file and it worked, for the first time I saw the decoder in action and it is very fast. Do you know if ffmpeg or mp4-box are able to extract mhas from mp4 container?
> 
> Hi @Emixjackox,
> 
> After commenting the line as suggested in the workaround, the build procedure is pretty much same the as procedure You followed for the first time build. Please let us know if you still face issues even with the workaround. Good to know that You are able to run level 3.
> 
> Regarding extraction of mhas from mp4, We have our own extractor tool as part of our [encoder ](https://github.com/ittiam-systems/libmpeghe) workspace.

Hello,

Could You try the suggested things ? Any updates
