### ISSUE TITLE
Extract individual objects?

### ISSUE THREAD

**Issue by sclsj** [ittiam-systems/libmpegh#19]
From my reading of other issues it seems like 360 Reality audio downloaded from Tidal is object-based, and during decode it is mapped to multichannel output. Is it possible to extract the individual objects? I really like the track and want to figure out what each instrument does in this as well as recreate parts on piano based on listening, and having objects (I assume one or a group of instruments?) isolated is very helpful for that.

For an example audio, please use [this track](https://drive.google.com/file/d/1lN6HH-5uOlh4Wdul-eWLAz9bpPhZQvQZ/view?usp=sharing). If this is not possible, if convenient please let me know of anything you can think of that might help me with this process. Thank you so much for your help!

**Comment by SakethSathuvalli** [comment]
Hi,

Please refer to our https://github.com/ittiam-systems/libmpegh/blob/main/docs/IA-MPEG-H-3D-Audio-Dec-GSG.doc and
https://github.com/ittiam-systems/libmpegh/blob/main/docs/IA-MPEG-H-3D-Audio-Dec-API.doc if any information is available for your use case.

Thanks!

**Comment by sclsj** [comment]
I'm sorry, I'm not very literate in this topic. I tried to read the guide but can't really understand it and so I can't find revevant information. Am I correct in understanding that this is not something I can do with the command-line program but something that might be possible by using the library?

**Comment by SakethSathuvalli** [comment]
Hi @sclsj,

Please refer to the entries in tables 3-1 and 3-2 of the [API document](https://github.com/ittiam-systems/libmpegh/blob/main/docs/IA-MPEG-H-3D-Audio-Dec-API.doc). These tables have details about the buffers that carry the object audio information when external rendering is enabled. The interfaces are provided as per the specification for MPEG-H and expects the user of this data to have prior knowledge of programming and digital audio formats(PCM data of multichannel).

Thanks!

**Comment by sclsj** [comment]
Unfortunately I do not know any programming language. Is there a demo or sample code that allows extraction of object data (i.e. MPEG-H 3d mp4 --> adm bwf) anywhere?

**Comment by SakethSathuvalli** [comment]
Hi @sclsj,

We have recently  added a wiki page on [external rendering interfaces](https://github.com/ittiam-systems/libmpegh/wiki/External-rendering-interfaces). Can You please check if it helps you with the issue you are facing?

Thanks!

**Comment by sclsj** [comment]
Hi @SakethSathuvalli 

It definitely helped. However, it seems like I'm getting a lot of popping noises, perhaps due to some problems with the limiter, for example limiter not applied and resulting in heavy clipping. How can I set a lower global gain (for example, multiple every gain for object by 0.5x so it won't clip)? Or maybe disable DRC for objects completely? I can't find an option for either.

**Comment by sclsj** [comment]
Below is an example. See the first 2 channels that are heavily clipped/limited.

<img width="2606" alt="截屏2023-01-31 11 21 26" src="https://user-images.githubusercontent.com/38654636/215819124-57791001-6ace-407e-88ca-29e3a7c21e21.png">

**Comment by sclsj** [comment]
I think these weird samples are why there are constant popping sounds. It seems like the clipped samples become negative? I'm not sure what's happening but it's definitely because the signal clipped.

**Comment by SakethSathuvalli** [comment]
> I think these weird samples are why there are constant popping sounds. It seems like the clipped samples become negative? I'm not sure what's happening but it's definitely because the signal clipped.
> 
> <img alt="截屏2023-01-31 11 21 22" width="2000" src="https://user-images.githubusercontent.com/38654636/215819477-e4dbbb6d-2255-4ce2-8128-334f4e4fbb50.png">

@sclsj, Can You please let know if the waveform shown above is of the audio data file generated using `-ext_ren:1` flag ?

**Comment by SakethSathuvalli** [comment]
Hi @sclsj,

Try once with our latest commit - [3b23f65](https://github.com/ittiam-systems/libmpegh/commit/3b23f65bf7750847e2a46c3092fda9b75ac60a26)

Thanks!

**Comment by sclsj** [comment]
Yes, it’s from the raw pcm generated by extren flag. I will try the latest commit.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Saketh Sathuvalli ***@***.***>
发送时间: Wednesday, February 1, 2023 2:33:17 AM
收件人: ittiam-systems/libmpegh ***@***.***>
抄送: Jin, Joy ***@***.***>; Mention ***@***.***>
主题: Re: [ittiam-systems/libmpegh] Extract individual objects? (Issue #19)


This email originated from outside Davidson College. Use caution, especially with links and attachments.


Hi @sclsj<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsclsj&data=05%7C01%7Cjojin%40davidson.edu%7C1df4472e39b24813b1a508db04269704%7C35d8763cd2b14213b629f5df0af9e3c3%7C1%7C0%7C638108336088116109%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=5CrfXNLwJXWeYVTFsY3N01oJ4cGQn3CXSfBZycDCe8Q%3D&reserved=0>,

Try once with our latest commit - 3b23f65<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fittiam-systems%2Flibmpegh%2Fcommit%2F3b23f65bf7750847e2a46c3092fda9b75ac60a26&data=05%7C01%7Cjojin%40davidson.edu%7C1df4472e39b24813b1a508db04269704%7C35d8763cd2b14213b629f5df0af9e3c3%7C1%7C0%7C638108336088116109%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Gyala4GxIocFodNUFPJR4SkUO4pRI2HDJzZVZQaMGc8%3D&reserved=0>

Thanks!

―

**Comment by sclsj** [comment]
> Hi @sclsj,
> 
> Try once with our latest commit - [3b23f65](https://github.com/ittiam-systems/libmpegh/commit/3b23f65bf7750847e2a46c3092fda9b75ac60a26)
> 
> Thanks!

It definitely worked.

However, the objects are still peak limited. How can I set a lower gain for objects?

**Comment by SakethSathuvalli** [comment]
Hi @sclsj,

The DRC effect will not be applied on the external renderer interfaces PCM output. It appears that the original content itself is peak limited in nature.

Thanks!

**Comment by SakethSathuvalli** [comment]
Hi @sclsj,

We would like to close this issue if You can confirm that you are able to extract individual objects with the `-ext_ren:` switch.

Regarding the gain, the decoder does not have a provision to apply desired gain on decoded objects.

Thanks!

**Comment by sclsj** [comment]
Thank you for all your help! Yes, I was able to use the ext_ren switch. Just want to confirm again that no processing is done to the decoded objects for extren, and all the drc metadata and such are included in the bitstream file?

**Comment by sclsj** [comment]
> Hi @sclsj,
> 
> Try once with our latest commit - [3b23f65](https://github.com/ittiam-systems/libmpegh/commit/3b23f65bf7750847e2a46c3092fda9b75ac60a26)
> 
> Thanks!

I'm still curious why that happened. From my experience you can exceed 0 dB in 24 bits? E.g. if I record in QuickTime the peak usually > 0dB and I have to apply like a -10dB gain. Even if 16 bit, shouldn't be audio just be clipped? I thought that's the normal behavior?

And also why would that happen in the first place? Shouldn't the encoded objects be peak normalized/limited in the first place (by the encoder)?

And could you explain how did you fix this (e.g. lower the gain?)?

**Comment by sclsj** [comment]
Also, it seems like the new version of libmpegh fails to decode 360 RA files from Deezer.

```
ia_mpeghd_testbench -ext_ren:1 -ifile:/Users/jin/Music/deemix\ Music/YOASOBI\ -\ THE\ BOOK\ 2/07\ -\ もしも命が描けたら.mp4 -ofile:mingdeemix.wav
-ifile:/Users/jin/Music/deemix Music/YOASOBI - THE BOOK 2/07 - もしも命が描けたら.mp4 -ofile:mingdeemix.wav 
                       ITTIAM SYSTEMS PVT LTD, BANGALORE
                             http:\\www.ittiam.com
                      IA_MPEG_H_3D_AUD_DEC_ARM $Rev: 1.2 $
                                        

fatal error: Ittiam mpegh_dec  core coder module :Initialization: : Initialization fatal error
```

**Comment by SakethSathuvalli** [comment]
> Also, it seems like the new version of libmpegh fails to decode 360 RA files from Deezer.
> 
> ```
> ia_mpeghd_testbench -ext_ren:1 -ifile:/Users/jin/Music/deemix\ Music/YOASOBI\ -\ THE\ BOOK\ 2/07\ -\ もしも命が描けたら.mp4 -ofile:mingdeemix.wav
> -ifile:/Users/jin/Music/deemix Music/YOASOBI - THE BOOK 2/07 - もしも命が描けたら.mp4 -ofile:mingdeemix.wav 
>                        ITTIAM SYSTEMS PVT LTD, BANGALORE
>                              http:\\www.ittiam.com
>                       IA_MPEG_H_3D_AUD_DEC_ARM $Rev: 1.2 $
>                                         
> 
> fatal error: Ittiam mpegh_dec  core coder module :Initialization: : Initialization fatal error
> ```

The failure could be because the stream configurations may not be supported by our decoder. Example the stream could belong to a higher profile level.

**Comment by SakethSathuvalli** [comment]
> > Hi @sclsj,
> > Try once with our latest commit - [3b23f65](https://github.com/ittiam-systems/libmpegh/commit/3b23f65bf7750847e2a46c3092fda9b75ac60a26)
> > Thanks!
> 
> I'm still curious why that happened. From my experience you can exceed 0 dB in 24 bits? E.g. if I record in QuickTime the peak usually > 0dB and I have to apply like a -10dB gain. Even if 16 bit (e.g. convert from 24 bit to 16 bit in-place in Audition on file with >0dB peak), shouldn't be audio just be clipped? I thought that's the normal behavior?
> 
> And also why would that happen in the first place? Shouldn't the encoded objects be peak normalized/limited in the first place (by the encoder)?
> 
> And could you explain how did you fix this (e.g. lower the gain?)?

The fix is related to limiting the upper and lower limits of a 24-bit data. These are referred to as saturation fixes.

**Comment by sclsj** [comment]
> > > Hi @sclsj,
> > > Try once with our latest commit - [3b23f65](https://github.com/ittiam-systems/libmpegh/commit/3b23f65bf7750847e2a46c3092fda9b75ac60a26)
> > > Thanks!
> > 
> > 
> > I'm still curious why that happened. From my experience you can exceed 0 dB in 24 bits? E.g. if I record in QuickTime the peak usually > 0dB and I have to apply like a -10dB gain. Even if 16 bit (e.g. convert from 24 bit to 16 bit in-place in Audition on file with >0dB peak), shouldn't be audio just be clipped? I thought that's the normal behavior?
> > And also why would that happen in the first place? Shouldn't the encoded objects be peak normalized/limited in the first place (by the encoder)?
> > And could you explain how did you fix this (e.g. lower the gain?)?
> 
> The fix is related to limiting the upper and lower limits of a 24-bit data. These are referred to as saturation fixes.

Can you tell me a bit more? I failed to get more information with basic search. Did you just clip the samples?

**Comment by SakethSathuvalli** [comment]
> > > > Hi @sclsj,
> > > > Try once with our latest commit - [3b23f65](https://github.com/ittiam-systems/libmpegh/commit/3b23f65bf7750847e2a46c3092fda9b75ac60a26)
> > > > Thanks!
> > > 
> > > 
> > > I'm still curious why that happened. From my experience you can exceed 0 dB in 24 bits? E.g. if I record in QuickTime the peak usually > 0dB and I have to apply like a -10dB gain. Even if 16 bit (e.g. convert from 24 bit to 16 bit in-place in Audition on file with >0dB peak), shouldn't be audio just be clipped? I thought that's the normal behavior?
> > > And also why would that happen in the first place? Shouldn't the encoded objects be peak normalized/limited in the first place (by the encoder)?
> > > And could you explain how did you fix this (e.g. lower the gain?)?
> > 
> > 
> > The fix is related to limiting the upper and lower limits of a 24-bit data. These are referred to as saturation fixes.
> 
> Can you tell me a bit more? I failed to get more information with basic search. Did you just clip the samples?

Yes, the samples will be clipped to maximum / minimum value if they are found to exceed.

**Comment by sclsj** [comment]
What should I do if I don't want it to clip? Is it possible to reduce the gain or to output as 32-bit float, which wouldn't have this problem?

**Comment by SakethSathuvalli** [comment]
For the individual objects it is not possible to apply gain.

**Comment by SakethSathuvalli** [comment]
Even when float output is given the values exceeding [-1.0, 1.0] will be clipped. However, support for float output is currently not available

**Comment by sclsj** [comment]
But is it possible to solve this one way or another? Clipping is still bad, although not nearly as bad as inverted samples.

**Comment by sclsj** [comment]
> Even when float output is given the values exceeding [-1.0, 1.0] will be clipped. However, support for float output is currently not available

I'm asking about float since QuickTime Player on macOS records in 24-bit float and every time I record most of the samples are > 0dB. I just do a -12dB volume reduction and it's ready to be used.

**Comment by SakethSathuvalli** [comment]
A not so clean way is to tap the output before clipping. This has to be done in the code. Please check the fix given for saturation overflow. It can help you with the buffer containing audio data that is not clipped.

Thanks!

**Comment by sclsj** [comment]
Emm... I just replaced that with `pcm_sample = pcm_sample * 0.5f` and it seemed to work... Other than increased noise floor, what problems might that cause?

**Comment by SakethSathuvalli** [comment]
When You try to apply gain on the output again the clipping behavior will be seen again when the data is stored as 16/24 bit PCM. Other than this I don't see any other implications.

Thanks!

**Comment by sclsj** [comment]
I don't think I understood you. Could you please explain more? Are you saying that if this 0.5 gain is not low enough for certain files, the ext_ren pcm will still be clipped? 

Thank you for all your help!

**Comment by SakethSathuvalli** [comment]
All I am saying is when You apply a gain of 2.0 or more on this output(`pcm_sample = pcm_sample * 0.5`), the samples will get clipped. 

The sample values exceed the range [-1.0, 1.0] by a very marginal value(< 1e-2). This is due to the implementation and is expected. Also this can happen even if the encoder takes care of clipping.

Thanks!

**Comment by sclsj** [comment]
Hello again! You locked #38 due to off-topic, so I'm unable to delete or hide my comment. You have my consent to delete or hide my comment.
