### ISSUE TITLE
Input File: File Open Failed 

### ISSUE THREAD

**Issue by notjsng** [ittiam-systems/libmpegh#22]
Hi, I am new to this, could someone help me? 
 

![image](https://user-images.githubusercontent.com/116333531/197118800-a6f89c79-7bfd-476f-83f4-e515fb59e03e.png)

**Comment by SakethSathuvalli** [comment]
Hi @notjsng,

Please place the file You.mp4 is in the same folder as `ia_mpeghd_testbench.exe`. Alternatively You can give the absolute path of the file.

If the file is already in the same location as `ia_mpeghd_testbench.exe`, then try running the command without " "(double quotes) around the file name.
