### ISSUE TITLE
Extracting Object only

### ISSUE THREAD

**Issue by TimsVolcanion** [ittiam-systems/libmpegh#26]
I'm currently testing out the decoder and I can't get it to extract the objects, I've checked the documents provided, it didn't give me any information.

**Comment by SakethSathuvalli** [comment]
Hi,

Please refer to the entries in tables 3-1 and 3-2 of the [API document](https://github.com/ittiam-systems/libmpegh/blob/main/docs/IA-MPEG-H-3D-Audio-Dec-API.doc). These tables have details about the buffers that carry the object audio information when external rendering is enabled. The interfaces are provided as per the specification for MPEG-H and expects the user of this data to have prior knowledge of programming and digital audio formats(PCM data of multichannel).


Thanks!

**Comment by m41c0n** [comment]
> Hi,
> 
> Please refer to the entries in tables 3-1 and 3-2 of the [API document](https://github.com/ittiam-systems/libmpegh/blob/main/docs/IA-MPEG-H-3D-Audio-Dec-API.doc). These tables have details about the buffers that carry the object audio information when external rendering is enabled. The interfaces are provided as per the specification for MPEG-H and expects the user of this data to have prior knowledge of programming and digital audio formats(PCM data of multichannel).
> 
> Thanks!

Hello,
I have a doubt: 
If a song is encoded with 22.2 channels, and I use your software to decode it with -cicp:19 (wishing for a 7.1.4 file), the conversion merges the channels to form the output, or it just erases the extra channels?
Thank you!

**Comment by SakethSathuvalli** [comment]
> > Hi,
> > Please refer to the entries in tables 3-1 and 3-2 of the [API document](https://github.com/ittiam-systems/libmpegh/blob/main/docs/IA-MPEG-H-3D-Audio-Dec-API.doc). These tables have details about the buffers that carry the object audio information when external rendering is enabled. The interfaces are provided as per the specification for MPEG-H and expects the user of this data to have prior knowledge of programming and digital audio formats(PCM data of multichannel).
> > Thanks!
> 
> Hello, I have a doubt: If a song is encoded with 22.2 channels, and I use your software to decode it with -cicp:19 (wishing for a 7.1.4 file), the conversion merges the channels to form the output, or it just erases the extra channels? Thank you!

Hi @m41c0n ,

The conversion merges the channels from output using an algorithm the takes into consideration the input and output channel formats. It does not erase the extra channels.

**Comment by m41c0n** [comment]
> 
> Hi @m41c0n ,
> 
> The conversion merges the channels using an algorithm which takes into consideration the input and output channel formats. It does not erase the extra channels.

Thank you so much for the answer!
And by the way, thank you for this amazing project, it's so useful and works perfectly...
Have a nice day.

**Comment by SakethSathuvalli** [comment]
Hi @m41c0n 

We have recently added a wiki page on [external rendering interfaces](https://github.com/ittiam-systems/libmpegh/wiki/External-rendering-interfaces). Can You please check if it helps you with the issue you are facing?

Thanks!

**Comment by SakethSathuvalli** [comment]
Hi @TimsVolcanion,

I was wondering if you got a chance to try the `-ext_ren:` command line switch for extracting objects. Here's a [wiki page](https://github.com/ittiam-systems/libmpegh/wiki/External-rendering-interfaces) that talks about this command line switch.

Thanks!

**Comment by SakethSathuvalli** [comment]
Hi @TimsVolcanion,

We will be closing this issue soon due to inactivity for long-time!
