### ISSUE TITLE
What are valid drc effect types?

### ISSUE THREAD

**Issue by sclsj** [ittiam-systems/libmpegh#35]
[-effect:<drc_effect_type>]
I can't find any documentation on what argument I can pass to this option. Is there a list of effects and what they do?

**Comment by SakethSathuvalli** [comment]
Hi @sclsj,

The effect types and their descriptions are part of the [MPEG-D DRC](https://www.iso.org/obp/ui/#iso:std:iso-iec:23003:-4:ed-2:v1:en) specification

**Comment by sclsj** [comment]
Thank you! Is there a specific page number / range you can give me to the list of options?

**Comment by sclsj** [comment]
OK. I saw it in Table A.45. But do I use the bit position, drcseteffect, or shortname?

**Comment by sclsj** [comment]
And how can I set a lower gain?

**Comment by sclsj** [comment]
It seems like it's still not working. For example, I tried `effect:10`, `-effect:"Fade-in"`, and `-effect:fade` which all produced the same result if the flag is not specified. I though if it doesn't change the DRC parameters (maybe a limiter to avoid clipping by default), it should at least change something?

**Comment by sclsj** [comment]
I'm mainly trying to get #20 fixed because I felt like there is definitely a limiter applied overall because from experimenting rendering of different channel layout it seems like individual objects are not heavily compressed. I'm trying to see what options will allow me to override the encoder settings to compress heavily.

**Comment by sclsj** [comment]
So all in all, is there any option / set of options that will allow me to override the default specification and preserve the dynamic range of the source material?

**Comment by SakethSathuvalli** [comment]
Hi @sclsj,

It is possible to extract un-rendered signals from the decoder using the `-ext_ren:` command line option. However, there is no option to avoid the DRC processing happening on the stream if DRC paylod is present in the encoded bit-stream.

You can refer to our wiki page on [external rendering interfaces](https://github.com/ittiam-systems/libmpegh/wiki/External-rendering-interfaces) for more information on using the option `-ext_ren:`

Thanks!

**Comment by sclsj** [comment]
Closing as duplicate of #20 and #19
