### ISSUE TITLE
Decoder crash due to invalid array indice read found during fuzzing tests

### ISSUE THREAD

**Issue by miartad** [ittiam-systems/libmpegh#36]
Hello,

I was running fuzzing tests on the decoder and found following issue:

1. amend CMakeLists.txt
```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index a0226d5..7fe656c 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -7,6 +7,9 @@ set(CMAKE_CXX_STANDARD_REQUIRED ON)
 set(CMAKE_CXX_EXTENSIONS OFF)
 set(CMAKE_SUPPRESS_REGENERATION true)

+add_compile_options(-fsanitize=address)
+add_link_options(-fsanitize=address)
+
 # Add Library Target
 add_library (
         ia_mpeghd_lib
```
2. and run following tests after build ([1.txt](https://github.com/ittiam-systems/libmpegh/files/10278546/1.txt) is a mhas file)

./ia_mpeghd_testbench -ifile:./1.txt -ofile:./1.wav

crashes because c = -1 in /impeghd_hoa_render_mtrx.c:191
beta = ia_hoa_beta_value_table[c];

**Comment by SakethSathuvalli** [comment]
Hi @miartad,

Thanks for bringing this up!

We too have come across this issue during our fuzzer testing. We will be uploading fix for this issue along with other issues seen at our end soon.
We will keep this thread open till then.

Appreciate your efforts for carrying out fuzzer runs on our workspace!

**Comment by SakethSathuvalli** [comment]
Addressed in #41.

Thanks!

**Comment by SakethSathuvalli** [comment]
Hello @miartad,

I was wondering if you got a chance to validate the fix pushed for this issue.

Thanks!

**Comment by miartad** [comment]
Hi @SakethSathuvalli 

I plan to do that this week, thank you for fixing the reported issues!

**Comment by miartad** [comment]
hi @SakethSathuvalli 

I checked against our crash logs, 6/8 fuzzer crash logs were fixed, but 2 still remain crashing, I can provide the example files that cause crashes later

**Comment by SakethSathuvalli** [comment]
Hi @miartad,

Are the 2 crashes happening with the same array or a different one ?

If different I suggest We close this issue and report the two crashes in a different thread/issue.

Thanks again for bringing up fuzzer issues !

**Comment by miartad** [comment]
Hi @SakethSathuvalli 

here are some more sample files that will produce crashes in unique places in code:
[crash-3.txt](https://github.com/ittiam-systems/libmpegh/files/10696122/crash-3.txt)
[crash-2.txt](https://github.com/ittiam-systems/libmpegh/files/10696123/crash-2.txt)
[crash-1.txt](https://github.com/ittiam-systems/libmpegh/files/10696124/crash-1.txt)

I could create a separate issue, as Im not sure whether these crashes are related...

**Comment by SakethSathuvalli** [comment]
> Hi @SakethSathuvalli
> 
> here are some more sample files that will produce crashes in unique places in code: [crash-2.txt](https://github.com/ittiam-systems/libmpegh/files/10696123/crash-2.txt) [crash-1.txt](https://github.com/ittiam-systems/libmpegh/files/10696124/crash-1.txt)
> 
> I could create a separate issue, as Im not sure whether these crashes are related...

If the crash locations are different than the ones mentioned in this issue, I recommend You to create a new issue.
Meanwhile we will check the new crashes and let us know our feedback.

Thanks!

**Comment by miartad** [comment]
thanks, I will create separate issue and we can close this one I believe.
