### ISSUE TITLE
Error with 22.2 Object Based files (Deezer/Amazon Music)

### ISSUE THREAD

**Issue by SonMaxime** [ittiam-systems/libmpegh#38]
Hi, I'm using your decoder for converting 360RA music files leaked on internet, especially files who apparently comes from Tidal (7.1.4) and works well, but I recently got 22.2 files who comes from Deezer & Amazon Music and I followed your instructions but I still keep getting error like these : https://github.com/ittiam-systems/libmpegh/issues/7, https://github.com/ittiam-systems/libmpegh/issues/23. I did the modifications on Visual Studio, rebranded the MP4 container of the files with MP4Box.
![image](https://user-images.githubusercontent.com/47661880/213150937-ee6e1ef4-9f5d-4275-a993-ec7417240cda.png)
![image](https://user-images.githubusercontent.com/47661880/213150987-cd26ad58-3efb-4548-a640-4939fc838a36.png)
![image](https://user-images.githubusercontent.com/47661880/213151127-5776ca44-ddcc-4bdd-966c-7417fa9aac7c.png)

**Comment by SakethSathuvalli** [comment]
Hi @SonMaxime, The workaround suggested in #1 works well only for streams which satisfy some conditions. A possibility is that the streams for which You are facing decode failure may have configurations that are not supported by our decoder.

Thanks!

**Comment by noHackses** [comment]
Do you plan on adding Level 4 MPEG-H decoding to your decoder in the future ?

**Comment by sclsj** [comment]
I was able to decode 360 RA (HQ) files downloaded by deemix. Also 22.2 target layout, some have as many as 24 objects, also LC@4 I believe. Which track/album are you looking at?

**Comment by SonMaxime** [comment]
> I was able to decode 360 RA (HQ) files downloaded by deemix. Also 22.2 target layout, some have as many as 24 objects, also LC@4 I believe. Which track/album are you looking at?

Koi Ha Ryusei by Minako Yoshida https://bayfiles.com/R0r2Y0W6y1/06_Yume_De_Aetara_mp4

**Comment by SakethSathuvalli** [comment]
We will not be supporting this issue as the source of the streams mentioned here doesn't sound appropriate

**Comment by sclsj** [comment]
> > I was able to decode 360 RA (HQ) files downloaded by deemix. Also 22.2 target layout, some have as many as 24 objects, also LC@4 I believe. Which track/album are you looking at?
> 
> Koi Ha Ryusei by Minako Yoshida https://bayfiles.com/R0r2Y0W6y1/06_Yume_De_Aetara_mp4

I actually can reproduce this on the current build (same behavior). However, I tried using a previous build (git clone) and it worked. It seems like I cloned the repository on 2022/10/13.
