### ISSUE TITLE
Full support for MPEGH_PROFILE_LC_LVL_4

### ISSUE THREAD

**Issue by amiartus** [ittiam-systems/libmpegh#49]
Hello,

Amazonmusic has "ultra" quality providing mpegh streams with MPEGH_PROFILE_LC_LVL_4 which is not fully supported (limited by channel count) with libmpegh at the moment.

Since this service is quite popular I would like to ask whether support for this profile and level is planned for future.

An example of such stream is Piano Man by Billy Joe on Amazon music

thanks!

Adam

**Comment by miartad** [comment]
Hi Christof,

thank you for your insightful comment.

Based on my understanding if LC4 is used by stream, this check in `decoder/ia_core_coder_init_config.c` will fail:

```
   if (dec_proc_core_chans > MAX_NUM_CHANNELS_LVL3 || ref_layout_chans > MAX_NUM_CHANNELS_LVL3)
    {
      return IA_MPEGH_DEC_INIT_FATAL_STREAM_CHAN_GT_MAX;
    }
```

because 
```
decoder/ia_core_coder_cnst.h:#define MAX_NUM_CHANNELS_LVL3 16
```

Hence why we were not able to decode the stream.

If I understand your comment correctly libmpegh may in case of LC4 and CompatibleProfileLevelSet() flag revert to BP3 and in that case in code check vs MAX_NUM_CHANNELS(24) will be used instead and the stream may potentially play.

However since this is decoder internals I assume the patch would have to be done to the libmpegh as AFAIK there is no way to produce this behavior just by using the decoder API.

Adam

**Comment by christof-fersch** [comment]
Hi Adam,

You are right. I didn't check what the code does, but from the description it should be supporting that scenario:

_State-of-the-art MPEG-H 3D Audio Low Complexity Profile decoders according to [ISO/IEC 23008-3:2019/AMD 2:2020](https://www.iso.org/standard/79147.html) also support the MPEG-H 3D Audio Baseline Profile, which is a subset of the MPEG-H 3D Audio Low Complexity Profile._

Have you been able to check the streams you are using and if they are in fact using the signalling as described?

Independent from that, I think the check should be changed according to what's standardised in AMD 2:2020 or the 23008-3:2022 version accordingly.

Thanks,
//Christof

**Comment by miartad** [comment]
Hi @christof-fersch, @SakethSathuvalli,

we tested decoding mpegh stream file from Amazon with "ultra" quality.

libmpegh currently does not implement CompatibleProfileLevelSet parsing and support in mp4 ext box or in decoder config as described in 2022 version of the standard.

The Amazon ultra streams that I tested do not use MHAProfileAndLevelCompatibilitySetBox or CompatibleProfileLevelSet in the mpegh3daConfigExtension. This leads me to believe even if the compatibility flag could be used, some ultra streams may not be able to be played, unless full LC LVL 4 support is implemented.

We were able to play and listen to at least one "ultra" stream when patching libmpegh to force decoding in LC LVL 3 mode.

Amazon streaming is a major use case, @SakethSathuvalli, are there any plans for implementing full LC LVL 4 decoding and the CompatibleProfileLevelSet as described by the 2022 standard?

Best Regards,
Adam

**Comment by SakethSathuvalli** [comment]
Hi @miartad,

We will be adding this support in decoder config in a week's time. Thanks for your patience!

Best Regards,
Saketh

**Comment by SakethSathuvalli** [comment]
Hi @adminitis,

Support for `CompatibleProfileLevelSet` landed on main branch today. Regarding Low complexity profile level 4, work is currently under progress. Support will be added in a few weeks.

Thanks,
Saketh

**Comment by bluewidy** [comment]
It looks like it is still not decoding profile level 4.

**Comment by bluewidy** [comment]
https://github.com/Fraunhofer-IIS/mpeghdec
This program supports decoding for profile level 4 and is open source. So you can refer to this.

**Comment by SonMaxime** [comment]
> https://github.com/Fraunhofer-IIS/mpeghdec This program supports decoding for profile level 4 and is open source. So you can refer to this.

Only with LC@L4/BL@L3 files unfortunately.

**Comment by benjamin-weiss** [comment]
@SakethSathuvalli I've seen you have been working on this recently. What are your plans on merging this to main?

**Comment by SakethSathuvalli** [comment]
> @SakethSathuvalli I've seen you have been working on this recently. What are your plans on merging this to main?

The changes are expected to be available on `main` branch - in the same form (enhancements maintained under build time switch) - by early June.

Thanks!

**Comment by SakethSathuvalli** [comment]
Initial version available on main branch. 
**Note:** The default build has support only till profile level 3, in order to enable support for profile level 4 the build switch `LC_LEVEL_4` has to be enabled.

Thanks!
