### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by miartad** [ittiam-systems/libmpegh#57]
Hello,

I have noticed the license information is split between README.md LICENSE and LICENSE2. This makes it less convenient for some build systems that collect this information.

Is there any particular reason why this information is split in this way? Are there any plans for only one license file in future?

**Comment by SakethSathuvalli** [comment]
Hi, 

Can You please elaborate the "less convenient" part?

Thanks!

**Comment by miartad** [comment]
- LICENSE and LICENSE2 refer to README file but this file does not exist. similar file named README.md is present, and this file additionally contains unrelated information to the license.

this makes things a bit ambiguous because of the file contents and naming, and requires to gather all 3 files for the license information. this is not a major problem, but it is more common to have only 1 license file per library.

**Comment by sandeshvenkatesh** [comment]
Hi,

GITHUB expected to use the exact same text of "BSD-3-Clause-Clear license" as-is without any modifications. Even with slight modification in the LICENSE text content, the license would not show up as "BSD-3-Clause-Clear license" in the home page. As there was a need to have few additional details as part of the license, splitting details across LICENSE and LICENSE2 was the only way. With this change, the additional details that was needed could be accommodated as well as retain "BSD-3-Clause-Clear license" in the homepage in GITHUB.

There are no plans for reverting to "one license" file in future as "two LICENSE" file structure was introduced for the above stated reason.

**Comment by benjamin-weiss** [comment]
I have to say, I find that questionable. If you add something to the "BSD-3-Clause-Clear license" it is not a "BSD-3-Clause-Clear license" anymore, but a modified "BSD-3-Clause-Clear license". So GitHub is correct in not showing it as a "BSD-3-Clause-Clear licensed" project in the home page.

**Comment by SakethSathuvalli** [comment]
Hi @benjamin-weiss,

Yes You are correct. Its overall a modified BSD-3-Clause-Clear license. The license information will be maintained in two files. There are no plans to change this in the near future.

Thanks!
