### ISSUE TITLE
Failed to decode mhas files

### ISSUE THREAD

**Issue by miartad** [ittiam-systems/libmpegh#59]
Hello,

these two files were decode-able previously but fail to decode on new master. Is this expected?

[O24_3_FD_Bl-3.mhas.txt](https://github.com/ittiam-systems/libmpegh/files/11879513/O24_3_FD_Bl-3.mhas.txt)
[O20_3_FD_Bl-3.mhas.txt](https://github.com/ittiam-systems/libmpegh/files/11879515/O20_3_FD_Bl-3.mhas.txt)

I did not do bisect on git, but I am certain we were able to decode these files in previous libmpegh version.

Adam

**Comment by SakethSathuvalli** [comment]
Hi @adminitis,

Thanks for bringing this to our notice!

We had a quick look at the decode failure. It's because of a misplaced error check in one of the recent pulls to the master. We will add a fix at the earliest.

Thanks!

**Comment by miartad** [comment]
confirmed fixed in main
