### ISSUE TITLE
Input File: File Open Failed

### ISSUE THREAD

**Issue by Mrsergo22** [ittiam-systems/libmpegh#67]
Hi!
Am I doing something wrong? cause I keep getting this error
This is the command i use:
E:\DECODER>ia_mpeghd_testbench.exe for %f in (E:/decoder/album/*.m4a); do ia_mpeghd_testbench -ifile:"%f" -ofile:"%~dpnf.wav"
-ifile:%f

my decoder is in this directory : E:\decoder\
files i want to decode in this directory : E:\decoder\album
![Снимок экрана 2023-08-02 161341](https://github.com/ittiam-systems/libmpegh/assets/85763255/b85ec901-d0b8-4757-a4f5-1b7586a816c5)

**Comment by sandeshvenkatesh** [comment]
Hi,

There seems to be an issue with the syntax used. Can you try below command:

_E:\DECODER>for %f in (.\album\*.m4a); do ia_mpeghd_testbench.exe -ifile:"%f" -ofile:"%~nf.wav"_

The decoded outputs get generated in "E:\decoder".
