### ISSUE TITLE
Add Support For Deezer 360

### ISSUE THREAD

**Issue by k-popfilters** [ittiam-systems/libmpegh#7]
i keep on getting a blinking cursor when using deezer 360 files

**Comment by k-popfilters** [comment]
![just hangs there](https://user-images.githubusercontent.com/105951186/175044396-0b930193-1d51-4255-bdbb-935da88c58ed.PNG) been waiting for like 20 minutes nothing is happening

**Comment by k-popfilters** [comment]
![after an hour i got this](https://user-images.githubusercontent.com/105951186/175060113-0d8b3bb7-be74-4af8-a032-abd30d8ecf1d.PNG)
after an hour of waiting i got this

**Comment by SakethSathuvalli** [comment]
Hello,

The file You shared is of profile level 4. Our decoder supports only up to profile level 3 and hence the decode failure is reported. 

We have another open issue and we have specified a workaround. Please refer to the link below:
https://github.com/ittiam-systems/libmpegh/issues/1#issuecomment-1064887503

Please follow the instructions in this link and try decoding once. We tried with this at our end and we are able to successfully decode the file You shared.

Thanks!

**Comment by k-popfilters** [comment]
oh yes thank you i will try it:)

**Comment by SakethSathuvalli** [comment]
> > Hello,
> > The file You shared is of profile level 4. Our decoder supports only up to profile level 3 and hence the decode failure is reported.
> > We have another open issue and we have specified a workaround. Please refer to the link below: [#1 (comment)](https://github.com/ittiam-systems/libmpegh/issues/1#issuecomment-1064887503)
> > Please follow the instructions in this link and try decoding once. We tried with this at our end and we are able to successfully decode the file You shared.
> > Thanks!
> 
> wait what do you mean by comment line 1483?

Please check the link below for the exact line:

https://github.com/ittiam-systems/libmpegh/blob/main/decoder/ia_core_coder_init_config.c#L1483

Comment this line and rebuild the executable.

**Comment by SakethSathuvalli** [comment]
**Code Commenting**
![CodeCommenting](https://user-images.githubusercontent.com/87962845/175073119-4caee834-09f8-49e9-8031-af2da3e8bf69.JPG)

Rebuild the executable

Console log screenshot 

![consoleLog](https://user-images.githubusercontent.com/87962845/175073569-429fd112-c46b-4f27-9235-789cfff081a5.JPG)

**Comment by k-popfilters** [comment]
i also got a fatal error

**Comment by k-popfilters** [comment]
![2](https://user-images.githubusercontent.com/105951186/175106120-5fe19d17-4999-49a7-bc2f-c5839df1781a.PNG)
![1](https://user-images.githubusercontent.com/105951186/175106125-68bab325-d8d4-45db-8074-cfec440c36c7.PNG)
 with this track https://drive.google.com/file/d/19SAMQdGH5cmL7YVM0X2mR0iSLr7ZhAgo/view?usp=sharing

**Comment by SakethSathuvalli** [comment]
> ![2](https://user-images.githubusercontent.com/105951186/175106120-5fe19d17-4999-49a7-bc2f-c5839df1781a.PNG) ![1](https://user-images.githubusercontent.com/105951186/175106125-68bab325-d8d4-45db-8074-cfec440c36c7.PNG) with this track https://drive.google.com/file/d/19SAMQdGH5cmL7YVM0X2mR0iSLr7ZhAgo/view?usp=sharing

Hi,

A preliminary look at the decode failure(after 5678 frames) of the file "01 - Love Me Land.mp4" gave us an impression that the file does not comply with MPEG-H low complexity encoding specifications. One such deviation from the MPEG-H low complexity profile restrictions is below:

The file's sampling frequency is **48000 Hz** and it uses **LPD mode** of encoding. According to the MPEG-H standard LPD mode is supported only for sampling frequencies **<= 32000 Hz**. The decoder is reporting an error on encountering such frame (Frame No: 5679) and as a result fails to decode further.

Will it be possible for You to share the source/mechanism used for creating this file? This can probably help us suggest You any option for encoding / recreating the file in decodable format.
 
 Thanks!

**Comment by k-popfilters** [comment]
I used deemix to get the songs

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by SakethSathuvalli** [comment]
Closing the issue as cause was [explained](https://github.com/ittiam-systems/libmpegh/issues/7#issuecomment-1163907219).
