### ISSUE TITLE
Fraunhofer test files fail with "invalid channel configuration"

### ISSUE THREAD

**Issue by MarkerB** [ittiam-systems/libmpegh#74]
I'm trying to verify the channel layout using the Fraunhofer "test signal" files, and the ia_mpeghd_testbench conversion fails with the error "invalid channel configuration". It fails no matter what channel layout I use on the command line. I've tried a "cicp" of 20, 19, and 7.

The Fraunhofer test files are located at [https://mpegh.com/test-signals/](https://mpegh.com/test-signals/), and I've specifically tried "Channel Identification: 7.1 + 4 Speakers".

I've been able to convert other mp4 wrapped MPEG-H files without incident, but I don't quite trust the channel mappings I'm getting. All my input files have the order "L R C LFE Lb Rb Lss Rss Tfl Tfr Tbl Tbr", but it would be great to hear a test for sure.

**Comment by SakethSathuvalli** [comment]
Hi @MarkerB,

Thanks for bringing this to our notice!

A quick fix is available on the branch - https://github.com/ittiam-systems/libmpegh/tree/74-fix-mp4-parse-issue

It will take us sometime (~1-2 weeks) to bring it on to `main` branch post testing and validation.

Thanks!

**Comment by MarkerB** [comment]
> A quick fix is available on the branch - https://github.com/ittiam-systems/libmpegh/tree/74-fix-mp4-parse-issue

Wonderful!  I had been using the ready-made Windows executable, so I had to install Visual Studio Community... but now I can convert those test files from Fraunhofer.  Thank you so much!
