### ISSUE TITLE
[QUESTION] Can I pay someone to explain how to use this like I'm a 5th grader?

### ISSUE THREAD

**Issue by tcafranz** [ittiam-systems/libmpegh#76]
I just want to decode the 360 audio files I got from tidal-dl and get the actual 12 or 24 wav files from each song. I'm familiar with some of this stuff but the rest is like reading hieroglyphics. I will literally pay someone to explain this like I'm a 5th grader.

**Comment by sclsj** [comment]
Are you familiar with the Terminal and channel layout <---> cicp?

**Comment by sclsj** [comment]
TL;DR
In Terminal run `ia_mpeghd_testbench -ifile:<drag 360 file here> -ofile:<drag it here again and replace the file extension with wav>`

**Comment by sclsj** [comment]
If you are using Windows, you can grab the compiled files from releases (both .lib and .exe)
If you are using Linux / macOS / etc:
``` 
$ git clone "https://github.com/ittiam-systems/libmpegh"
$ cd libmpegh
$ mkdir bin
$ cd bin
$ cmake ..
$ cmake --build .
```
