### ISSUE TITLE
Off-by-one issue in maximum number of description languages check

### ISSUE THREAD

**Issue by benjamin-weiss** [ittiam-systems/libmpegh#78]
The check in https://github.com/ittiam-systems/libmpegh/blob/main/decoder/impeghd_mhas_parse.c#L85 should be changed to 
```c
if (pstr_description_data->num_descr_languages[blk] > MAX_NUM_DESCR_LANGUAGES)
```
to actually allow the maximum of 4 description languages.

**Comment by SakethSathuvalli** [comment]
Hi @benjamin-weiss,

Thanks for bringing this up!

Can You please let know if this issue was discovered by code inspection (or) any specific test condition? - The information can help us improve our regression testing - test suite.

Thanks!

**Comment by benjamin-weiss** [comment]
We discovered this with a test file, but unfortunately I am not allowed to share it with you.

**Comment by SakethSathuvalli** [comment]
Thanks! Will it be possible to share the set of command line options / switches used for this testcase ?

**Comment by SakethSathuvalli** [comment]
@benjamin-weiss - we will have this fix on Main by next week. Thanks again for bringing this to our notice!

**Comment by SakethSathuvalli** [comment]
The fix is now available on latest main
