### ISSUE TITLE
Bitstream pointer has to be aligned to payload length after parsing

### ISSUE THREAD

**Issue by benjamin-weiss** [ittiam-systems/libmpegh#80]
We have another mpegh stream which cannot be decoded with the ittiam decoder. But again I can unfortunately not share it with you. But we identified the problem and I attached a patch to fix it. The problem is that ID_EXT_ELE_PROD_METADATA is not handled properly inside `ia_core_coder_ext_element_config()`. The unused payload bits are not skipped. Extension payload length is specified in bytes but actual payload length may be shorter. The unused bits are skipped for other cases but apparently it was forgotten to do it for this one.
[align_bitstream_pointer.txt](https://github.com/ittiam-systems/libmpegh/files/15250436/align_bitstream_pointer.txt)

**Comment by SakethSathuvalli** [comment]
Thanks for reporting this and sharing a possible fix as well! We will check this and get back to you.

**Comment by SakethSathuvalli** [comment]
Hi @benjamin-weiss,

This is now available on the main branch. The version number will be updated post the merger of lc-level-4 branch.

Thanks!
