### ISSUE TITLE
Versioning out of sync

### ISSUE THREAD

**Issue by benjamin-weiss** [ittiam-systems/libmpegh#85]
Hi,

in https://github.com/ittiam-systems/libmpegh/issues/80#issuecomment-2153907491 you mentioned that you will update the version after the LC4 PR is merged. Looks like this did not happen yet and the versioning has gotten a bit out of sync again. Currently I see

1. the `LIBVERSION` define is at 1.1 (https://github.com/ittiam-systems/libmpegh/blob/main/decoder/ia_core_coder_definitions.h#L39)
2. the CMake project version is at 1.3 (https://github.com/ittiam-systems/libmpegh/blob/main/CMakeLists.txt#L3)
3. the `MPEG_H_3D_AUD_DEC_ITTIAM_VER` define is at version 1.6 (https://github.com/ittiam-systems/libmpegh/blob/main/decoder/impeghd_ver_number.h#L39C9-L43)

Also there is no tag yet for the latest version. Thanks!

**Comment by SakethSathuvalli** [comment]
We will address 1. and 2. with #86

We will add tag only after we update documentation (We will rise an issue to track this).
